= Command Line Argument Interpreter Package
Tom Dilatush (tom@dilatush.com) +
V1.0, 2021-01-03
:toc:
:toc-placement!:
toc::[]

== What is a Command Line Argument Interpreter?
If you're writing a command line program (or server daemon), you're most likely going to want to provide for command line arguments.  For example:
....
myapp -c=12 -q --site=https://comic.com ~/myfile.txt
....
This might be a command that reads the site https://comic.com (the `--site https://comic.com`) twelve times (the +
`-c=12`), does it quietly (the `-q`), and puts the result in ~/myfile.txt (the `~/myfile.txt`).  This is all very standard in the Unix/Linux world, and to some extent even under Windows.  However, actually _writing_ the code to interpret all that is a pain in the patoot - especially if you want decent error checking, the expected help, etc.

The whole purpose of this package is to make that effort easier.  _Much_ easier, and also less error-prone.

== The notion of "arguments"...
In the example immediately above, we see four arguments (the stuff following `myapp`):

[start=1]

. The `-c=12` is an _optional_ argument with the short name `c` and an argument parameter `12`.  The `=` separates the short argument name from its parameter.  This parameter looks like a number to us, and the program needs to use it as a number, but on the command line it's two text characters: '1' and '2'.  Somewhere inside the program it has to be parsed and translated into the number 12.

. The `-q` is also an _optional_ argument, but with no parameter.  We call that a _binary_ optional argument, and it
has the value _true_ if it is present on the command line, and _false_ otherwise.

. The `--site=https://comic.com` is yet another optional argument, but this time with the long name `--site`.  It has a parameter (`https://comic.com`).  Note that the parameter immediately follows the long argument name and is separated from it by an equals (`=`) just as we saw with the first argument.  In this case the parameter is a string, but it's obvious to a human reader that that string is a URL - and that's also what the program expects.  Somewhere inside the program that string has to be parsed, validated, and converted to a URL.

. The `~/myfile.txt` is a path to a file, and there's no optional argument name before it.  That's because it's not an optional argument at all, but rather a _positional_ argument.  The meaning of a positional argument depends on exactly where it is on the command line, ignoring any optional arguments.  In this case it's the first (and only) positional argument.

=== The rules for arguments

* Short optional argument names are just a single character long, preceded by a single hyphen ("-"), like `-q`.  Multiple options with a short name may be grouped after a single hyphen, like `-qv` which is interpreted exactly as `-q -v` would be.  Options with short names _may_ have a parameter, which is specified by an equals (`=`) immediately following the short option name, immediately followed by the parameter, like `-c=15`.  If multiple options with a short name are grouped after a single hyphen, then only the last option can have a parameter, like `-qvc=15` - an arrangement like `-qc=15v` is invalid.  An option with a short name and a parameter that contains whitespace can be specified by quoting the entire option, like `"-f=/home/Rocky Balboa"`.  Any non-whitespace character may be used as a short argument name, with the exceptions of "-" and "=" (and we hope the reason for those exceptions is obvious!).  Conventionally the short argument name characters are in the range `[a-zA-Z0-9?]`, though that is not required.

* Long optional argument names can be one or more characters long, preceded by a double hyphen (`+--+`).  They _may_ have a parameter, which (as above) are specified by an equals (`=`) followed by the parameter's value, like `--name=Rocky`.  Again, if the parameter contains whitespace, the entire option must be quoted, like +
`"--namespace=Rocky Balboa"`.  Any non-whitespace characters may be used in a long argument name, except for "=" (and again we hope the reason for this exception is obvious!).  Conventionally the long  argument names are comprised of characters in the range `[a-zA-Z0-9_]`, though that is not required.

* Positional arguments have no names at all; how they are interpreted depends entirely on their relative position on the command line, after ignoring any optional arguments.  Note that while optional arguments are conventionally written _before_ the positional arguments, this is not actually required.  For instance, we could have written our example as `myapp -c=12 -q ~/myfile.txt --site=https://comic.com` without any change in its meaning.  Generally positional arguments may appear only once, and they must appear in a particular order; this is (almost) the only way to guarantee an unambiguous interpretation of them.  There is, however, one important exception: for any given command line, there may be at most _one_ positional argument that may have multiple values.  This is particularly useful when handling https://tldp.org/LDP/abs/html/globbingref.html[globbing].  That one positional argument that can accept multiple values may be in any position; it doesn't have to be the first or the last.  Positional arguments _can_ contain whitespace, but only if they're quoted.  For instance, the command line `myapp a "b c"` has just two positional arguments, not three.

* A single hyphen (`+-+`) appearing on the command line with whitespace on both sides is a special case - it is treated exactly as if you had an optional argument with a short name of hyphen ("`-`").  This special case cannot have a parameter; it can only be a binary optional argument.

* A double hyphen (`+--+`) appearing on the command line with whitespace on both sides has a special meaning: everything appearing after it on the command line is considered a positional argument, even if there are words that start with a hyphen.  For example, `+mycommand -c -- -d+` would treat the `-c` as an optional argument, and the `-d` as a positional argument.

=== A note about standards...
A sharp-eyed observer will note a small divergence from common command-line syntax in the argument descriptions above.  Specifically, when an argument has a parameter (like `-c=12`), there is an equal sign (`=`) separating the argument name from the parameter.  For many applications, arguments with single character names may be separated from their parameters by whitespace (like `-c 12`).  In this package we decided _not_ to allow this, mainly because it can lead to command lines with ambiguous interpretations.  By requiring the equals sign, all of these potential ambiguities are eliminated in a very simple way.

== How Does the Command Line Interpreter package work?
It's all well and good to have a command line interpreter, but if you're going to make use of it then you'll have to understand just a bit about how it works!
[start=1]
. *Defining*: Your application must _define_ the expected arguments (both optional and positional) on the command line.  This is quite straightforward in concept, though there are lots of details.  Basically you create an argument definition (an instance of ArgDef or one of its many subclasses) for each argument your application needs to understand, and then you add those argument definitions to a command line definition (an instance of CommandLine).
. *Parsing*: This is very simple: you pass the command line arguments your application got in its main() method to the parse() method of your CommandLine instance.  If the result is valid, it contains the values of all the defined arguments (including a default value if the argument wasn't present on the command line).  If the result is invalid, it contains an explanatory error message.
. *Using*: If the result of parsing was valid, then your application can retrieve (by name) each argument's value.  That's the end goal of this package - a simple and straightforward way to use the command line arguments.

== Argument Definitions
Getting these right are the key to using this package effectively.  There are two kinds of argument definitions: positional and optional, with the latter having a few additional fields.  Both of these are simple immutable POJOs created with a straightforward constructor.

=== Argument definition fields for both optional and positional arguments
- *referenceName*: This is the name your application's code uses to refer to a particular argument.  It can be any string, so long as that string is unique amongst all the arguments defined for a given application.  This name is invisible to a user of your program.

- *summary*: A short help message for this field, which will be included in the summary help.  There are no rules for the length of this string, though ideally it will fit on a single line.

- *detail*: A longer, more detailed help message for this field, which will be included in the detailed help.  Ideally this will be similar to what one would find in a man page.

- *maxAllowed*: The maximum number of times this argument may appear on the command line.  Zero is a special value that indicates there is no limit.  Most of the time this value will be a 1 (one), but there are some important exceptions.  For instance, a positional argument for a file name might be globbed, and therefore could have any number of appearances.  Another example might be an optional argument that increases the verbosity of an application's output more and more the more times it appears, up to some limit.  This is often seen as the short argument "-v", allowed to appear four or five times.

- *helpName*: A user-visible name for the parameters of optional arguments or for positional arguments.  This name will appear in both summary and detailed help, as well as in error messages for invalid command lines.

- *type*: The Java class object for the type of the argument's value.  This _could_ be String.class for every argument, which is how the argument parameters appear on the command line.  This would be a shame, however, because it would miss a lot of the power of this package.  Every argument definition includes an optional ParameterParser instance.  These are discussed in detail in their own section, but basically they translate the parameter string on the command line into a value of whatever type you want.  These could be numbers, InetAddress instances, File instances ... or whatever.  This built in translation capability makes your application code simpler - always a good goal!

- *parameterMode*: This is an enum that specifies whether the argument's parameter is allowed; it has these possible values:
** *DISALLOWED*: This value is only allowed for optional arguments.  If the command line specifies a parameter, the parser will fail with an explanatory message.
** *OPTIONAL*: This means slightly different things for the different argument types:
*** Optional arguments: if the argument is specified on the command line, then a parameter is allowed but not required.  If the command line does not specify a parameter, then the parser will use defaultValue (see below) and optionally a parser to provide a value.
*** Positional arguments: Means that the argument may or may not be specified on the command line.  If it is _not_ specified, then the parser will use defaultValue (see below) and optionally a parser to provide a value.
** *MANDATORY*: This means slightly different things for the different argument types:
*** Optional arguments: If the argument is specified on the command line, the user _must_ also specify a parameter.  There is one exception to this: if the argument's definition allows interactive mode, then the parameter could be absent from the command line, and the parser will prompt the user for it to be entered interactively.
*** Positional arguments: The argument _must_ be specified on the command line.

- *defaultValue*: The default value for this argument's parameter if it is not specified on the command line.  If the argument definition includes a parser, the default value will be parsed by that parser to produce the actual value returned.

- *parser*: The optional parser for use with this argument.  The parser translates the parameter string into an object of any type.  This is very useful for things like translating file paths to File objects, or numeric values to Integer objects.  A parser may also provide some kinds of validation; for example, a parser that translated paths to File instances might also verify that the resulting file is readable.

- *validator*: The optional validator for use with this argument.  The validator examines the parameter value to see if it is valid.  For example, you might have a validator that checked to see if the number given for a port was within the allowable range.  You might also have a validator that checked to see if a URL returned a valid page.

=== Additional argument definition fields for optional arguments
* *shortNames*: A string array of the single-character short names for this argument.
* *longNames*: A string array of the long names for this argument (these may be any length).
* *absentValue*: This is the parameter's value if the argument was not specified on the command line.  This string value is translated by the optional parser in this argument definition, if it is specified.
* *interactiveMode*: Specifies whether interactive parameter specification is allowed for this argument:
** *DISALLOWED*: The parser will not capture the parameter value interactively.
** *PLAIN*: The parser will capture the parameter value interactively if it is not specified on the command line.  The value entered by the user will be visible on the screen.
** *HIDDEN*: The parser will capture the parameter value interactively if it is not specified on the command line.  The value entered by the user won't be visible on the screen (generally asterisks will be displayed instead of what was actually entered).


== Special cases
There are two arguments that are a bit special:

- *Single hyphen ("-")*: When a single hyphen appears as an argument (white space before and after) on the command line, by convention it means that the program is going to get its input from stdin, or send its output to stdout.  In this package, the single hyphen parameter is a special case of an optional argument with a short name of hyphen ("-").  Ordinarily that would mean that you'd specify it on the command line as "--" (with the first hyphen indicating a short name, and the second hyphen being the actual name).  In this special case, the single hyphen _implies_ the short name of a single hyphen.  Any meaning attached to this argument (including the conventional meaning mentioned earlier) is outside the scope of this package and up to the program implementor.

- *Double hyphen ("--")*: This argument is not presented in the results of the parser, but is used by the parser to modify its behavior.  Normally any argument on the command line that starts with a hyphen ("-") is treated as an optional argument.  If the double hyphen appears on the command line, then _all_ arguments appearing after it (that is, to the right of it) are treated as positional arguments, even if they start with a hyphen.

== Parameter Parsers

Parameter parsers perform a simple, but powerful, service for this package.  They translate a string parameter (as specified on the command line) into an instance of any desired Java type.  Any particular parser must always translate to a particular type, but there's no restriction on that type.  Several parameter parsers are provided as a standard part of this package, and it's very straightforward to create a custom one.  Parameter parsers are particularly useful in situations where you find yourself creating the same translation code repeatedly in different programs.  The parsers provided with this package are all great examples of that.

== Parameter Validators

Just like parameter parsers, parameter validators also provide a simple, but powerful service.  In their case they provide a way for this package (instead of your code!) to provide validation of the command line - including providing a meaningful explanatory message.  This package comes with a number of validators that you can reuse.  They are very simple to write, so you could easily make a custom one for your own use.

== Getting parameter values from environment variables
Sometimes getting a value from the command line, or a shell script, is not really what you want.  One classic example is a password - you really don't want someone to see it, and you certainly don't want it in your shell script.  Another example might be the path to some file needed in a shell script, where the path might be different on different machines, but it would be nice to have a single shell script.  You _could_ enter the path as an argument every time you ran the script, but that's a pain no matter how you slice it.  Environment variables are a nice solution to both issues, if only we could use their contents as parameter values - and you can!

This package looks at any parameter value (whether on the command line, a default value, or an absent value) to see if it is in the form "%NAME%", and if so, it interprets "NAME" as the name of an environment variable, and substitutes the contents of that environment variable as the value of that parameter.  Note that the first and last characters of the parameter value must be a "%", and _everything_ between them is used as the environment variable name.

For the two examples given above, this gives you a nice solution.  For the password, you could define an optional argument with an optional parameter - and a default value like "%PASSWORD%".  This way if you leave the parameter off the command line, the default value will be extracted from the environment variable PASSWORD.  Similarly, for the file path example you could define a mandatory argument with an optional parameter - and an absent value like "%IMPORTANT_FILE_PATH%".  In this case if the argument isn't specified on the command line at all, it will get its value from IMPORTANT_FILE_PATH.  If the argument _is_ specified on the command line, then its value will be equal to the parameter entered by the user.

If a parameter value specifies an environment variable, but that variable does not exist, then the parameter value is the empty string ("").

== Getting parameter values from files
In a manner very similar to the way this package can get parameter values from environment variables (as described above), it can also get parameter values from text files.  To do this, any parameter value (whether on the command line, a default value, or an absent value) can be in the form "+#FILE_PATH#+".  In this case the FILE_PATH is treated as a (wait for it!) file path, and if there's a readable file at that path its contents are used as the parameter value.  Simple!  If the file path doesn't resolve to a readable file, then the parameter value is the empty string ("").