= DNS Resolver
Tom Dilatush (tom@dilatush.com) +
V1.0, 2021-09-04
:toc:
:toc-placement!:
toc::[]

== What exactly is the DNS Resolver?
It's a package that implements, in pure Java, a DNS resolver.  Shocking surprise, that!  A DNS resolver communicates with DNS servers to answer questions about a domain name.  The most common question asked is "What is the IP address associated with this domain name?" -- but there are many other questions that may be asked (and potentially answered) as well.

== Features
The DNS Resolver has a few features:

* It can resolve from accessible recursive DNS servers, such as those provided by Google, OpenDNS, and many ISPs.  The main advantages of this approach is reduced network traffic between the DNS Resolver and the recursive DNS server, and (possibly) speed due to the recursive DNS server's large cache shared across many users.  The disadvantages include allowing the owner of the recursive DNS server to snoop on things like what web sites you visit, the need to provision one or more recursive DNS servers to run the DNS Resolver, and being subject to the recursive DNS server's blacklisting of domain names that they disapprove of.
* It can resolve by iteratively interrogating authoritative DNS servers.  This is the same approach that the recursive DNS servers use themselves.  The main advantages of this approach are security and privacy (the Googles of the world don't know what you're doing), the absence of any provisioning requirement, and the absence of any sort of censorship.  The disadvantages include more network traffic between the DNS Resolver and the Internet, and (possibly) lower speed because there are fewer cached records.
* It has a cache whose size is configurable.  Even a small cache of 1,000 DNS resource records makes a very large difference in the DNS Resolver's performance.
* It has a convenient API that allow synchronous queries (where the calling thread blocks until the answer is available) and asynchronous queries (where the calling thread is not blocked, and the answer is provide by invoking a caller-provided handler).  Whether synchronous or asynchronous, the API provides methods for anything from very specific queries (for instance, for IPv4 addresses) to very general queries (for example, returning all the DNS resource records for a particular domain).
* The network input/output is all handled using Java's NIO package.  The main benefit of this approach is that a minimum number of threads are used.  In the DNS Resolver, this is particularly relevant when using iterative resolution, as even for a single query to the DNS Resolver there can be dozens of queries to DNS servers all being processed concurrently.

== Known limitations
There are a number of features that one might expect in a DNS resolver that this DNS Resolver does not implement:

* Reverse lookup: It cannot look up the domain names associated with an IP address.  For example, it will not query with the IPv4 address "42.82.78.210" to see what domain name resolves to that address.
* Negative caching: It does not cache negative responses.  If you queried for (let's say) "xyz.abc.net" and got an error, that error is not cached -- so if you queried for "xyz.abc.net" a second time, that query would not be resolved from the cache, but would instead result in a series of queries to the relevant DNS servers.

== Why did the author inflict this monstrosity on us?
It all started with the desire to make a UDP "pinger" that could test connectivity to a known IP address.  DNS servers, by their very nature, are at well-known IP addresses, so they make a good target.  UDP being a connectionless protocol, to implement a pinger I needed something that could send a well-formed query to the DNS server and listen for a response.  It seemed a small step to go from that to an actual fully-formed DNS resolver.  That turned out to be a rather large small step, but ... here it is.

== Theory of Operation

=== The life of a query
.  Query constructed
.  ID assigned
.  Stuffed into a map, indexed by ID
.  Query encoded
.  Query sent to DNS server
.  If it times out (because the DNS server doesn't respond quickly enough)
..  Remove the query from the map
..  Complete query with not ok, timeout
.  If the DNS response is received
..  If the response can be decoded
...  If the ID can be found in the map
....  Remove the query from the map
....  Complete query with ok, and received message
...  If the ID cannot be found in the map
....  Log the event
....  Discard the message
.. If the response cannot be decoded (garbled)
...  Log the event
...  Discard the message
